### ISSUE TITLE
[BUG] Error on every function using "Path" class on Windows

### ISSUE THREAD

**Issue by R4z1xx** [Lookyloo/PyLookyloo#43]
Hi there,

I've experienced an issue on multiple "get_" (and probably others that I haven't checked) function that use the "**Path**" class to construct the requested API URL.
Error example : 
```
Traceback (most recent call last):
  File "C:\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
...SNIP...
  File "C:\pylookyloo\api.py", line 95, in get_status
    return r.json()
  File "C:\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

After a bit of research i find that the issue was caused by this "Path" class which constructs the URL with **backslash** instead of normal slash under Windows. For example : 
`https://lookyloo.circl.lu/json\UUID\status`

It happened only on Windows and I have NO problem on Linux, it just build URLs normally.

I've created this issue for people who use Windows for development and may encounter the same problem.

Congrats for this tool, it's insane !

**Comment by R4z1xx** [comment]
Hi ! 

I've tried using `as_posix` in this line from the `get_status` function and it works well : 
`url = urljoin(self.root_url, str(Path('json', tree_uuid, 'status').as_posix()))`

I've currently experienced only this issue but if I find another one while testing it on Windows, I'll let you know !

**Comment by R4z1xx** [comment]
Perfectly working with this version !

**Comment by Rafiot** [comment]
Nice! Thank you for the feedback, I'm going to implement the same thing in a bunch of other libraries :)
